title: Atal's website
author: Atal
email: atal.nazim.an@gmail.com
theme : minima
description: Probably a blog
# social links
twitter_username:  Un_Mec_Rand0m
github_username:  AtalNazim

show_excerpts: true # set to false to remove excerpts on the homepage
